### ISSUE TITLE
'Observe' sends duplicate messages to the same target

### ISSUE THREAD

**Issue by eduardobs79** [rjrodger/seneca-balance-client#14] opened 2016-04-25 14:34 UTC
The add_target function should handle duplicate targets to avoid flooding a particular target.

**Comment by dgonzalez** [comment] 2016-05-01 21:57
As far as I am aware @rjrodger fixed the duplicated target few days ago (now the ID is checked before adding it to the authoritative list). Do you have any example where this is happening? can you pull the latest version and confirm that the problem is gone?

This commit: https://github.com/rjrodger/seneca-balance-client/commit/3b91622723827028d9e108a8b5c5a2eaee92df56

Fixes the duplicated target problem

**Comment by mcdonnelldean** [comment] 2016-05-02 08:19
@dgonzalez I'd say this is NodeZoo. I'm due to do a test run over the next couple of days so I can check this.

**Comment by eduardobs79** [comment] 2016-05-02 08:21
@mcdonnelldean @dgonzalez This was found in NodeZoo.

**Comment by mcdonnelldean** [comment] 2016-05-02 08:22
@eduardobs79 Do you have any logs or anything to show the multiple messages? If not, how did you figure it out? I'm looking for steps to reproduce the problem. This could be a potential performance hog so I'm keen to see if it's still broken :D

**Comment by mcdonnelldean** [comment] 2016-05-12 12:21
Fixed in release.

**Closed as completed by mcdonnelldean** 2016-05-12 12:21 UTC
Labels: investigate
